name: Publish-Extension

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     publish_extension:
  #       description: '是否发布到 VSCode Marketplace'
  #       required: true
  #       type: boolean
  #       default: 'true'

jobs:
  build:
    # if: github.event.inputs.publish_extension=='true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SetUp Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
      - name: Create Tag
        id: tag
        run: |
          git config user.email ${{ secrets.USER_EMAIL }}
          git config user.name ${{ secrets.USER_NAME }}
          yarn install && yarn release
          echo "::set-output name=release_tag::$(git describe --abbrev=0 --tags)"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Get Release Notes
        uses: yashanand1910/standard-release-notes@v1.2.1
        id: get_release_notes
        with:
          version: ${{ steps.tag.outputs.release_tag }} # Required
          # changelog_path: ./CHANGELOG.md # Optional
      # - run: echo ${{ steps.get_release_notes.outputs.release_notes }}
    outputs:
      RELEASE_TAG:  ${{ build.steps.tag.outputs.release_tag }}
      RELEASE_NOTES: ${{ build.steps.get_release_notes.outputs.release_notes }}

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Package Extension
        run: yarn package
      - name: Release Extension
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.RELEASE_TAG }}
          body: ${{ needs.build.outputs.RELEASE_NOTES }}

      #     files: "./*.vsix"
      # - name: Publish Extension
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      #     registryUrl: https://marketplace.visualstudio.com
